### PR TITLE
Introducing async client interaction #15

### PR DESCRIPTION
**Pull request by liqweed**
A preliminary commit to support asynchronous invocations of dgraph tansactions.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph4j/18)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/io/dgraph/Transaction.java, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph4j/18#-Kya-wNmE3SEjznva6OI:-Kya-wNmE3SEjznva6OJ:b-z95t4g) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/1f12290f084a990fd817cfb20f7f11fbb258d17e/src/main/java/io/dgraph/Transaction.java#L161)):*
> ```Java
>     for (Map.Entry<Integer, Long> entry : src.getIdsMap().entrySet()) {
>       if (dst.containsIds(entry.getKey())
>         && dst.getIdsOrThrow(entry.getKey()) >= entry.getValue()) {
> ```

if dst value is < the src, then dst should be updated. We're taking the max essentially.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph4j/18)*

**Comment by liqweed** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/io/dgraph/Transaction.java, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph4j/18#-Kya-wNmE3SEjznva6OI:-KyaNml6Hz7wdu-kQdDe:bew0lmr) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/1f12290f084a990fd817cfb20f7f11fbb258d17e/src/main/java/io/dgraph/Transaction.java#L161)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if dst value is < the src, then dst should be updated. We're taking the max essentially.
</blockquote></details>

That's copied verbatim from the original `DgraphClient#mergeLinReads()` (line 73).
I'll push a fix (basically switching `>=` with `<`).

Can you please elaborate on the role of `LinRead` in the Transaction design?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph4j/18)*

**Comment by manishrjain** [comment]
Dgraph does consistent replication. But, a replica could potentially be slightly behind the quorum in terms of applying the updates. LinReads would cause a replica to wait to catch up until the proposal id provided by lin reads map. Thus, this would ensure that a single client would always see updates going forward in time; never returning any stale reads.

**Comment by liqweed** [comment]
Any comments?

**Comment by liqweed** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/io/dgraph/Transaction.java, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph4j/18#-Kya-wNmE3SEjznva6OI:-KygLkGMIv8HB-u6wbuP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/1f12290f084a990fd817cfb20f7f11fbb258d17e/src/main/java/io/dgraph/Transaction.java#L161)):*
<details><summary><i>Previously, liqweed (Ophir Radnitz) wrote…</i></summary><blockquote>

As the project is currently lean on tests, I'll go ahead and push a fix and follow up with the tests a little later.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph4j/18)*

**Comment by deepakjois** [comment]
Hi @liqweed 

I cannot merge the PR as is because it contains extraneous stuff like the `.editorconfig` and some bug fix to the logic which doesn’t directly relate to the async client itself. Ideally, we would have a separate PR for that, and keep this PR focused on just the async client stuff. However, I have taken note of the bug in merging LinReads and pushed a fix already. I will incorporate your test as well, if you don’t mind.

I skimmed through your code,  and I have a few questions regarding how you are doing this. Let’s discuss and agree on some things, before moving forward with the PR. You could also hop on to the Slack channel between 0230-1130 GMT.

Ideally, I would like to have a `DgraphClient` for regular sync calls, and `DgraphClientAsync` for async calls. The method names and signatures would remain the same. Only the return values would differ. 

It would be nice to use the `DgraphBlockingStub` for synchronous calls, and `DgraphFuturesStub` for asynchronous calls with a thin layer of abstraction on top of them to expose a common interface. Is that possible? If that is not something that’s possible, I guess the alternate solution like you suggested already is to wrap the future in a CompletableFuture and block on it, and return the value in the regular synchronous client. What do you think?

The rest of the client code (including the building up of protobuf class objects) be re-used between the sync and the async client. Right now, your code is repeating some of that.

**Comment by deepakjois** [comment]
Oh, and right now we use `google-java-format` to format our code. We use Go on our team primarily, and we are comfortable with the way Go code is formatted automatically using `go fmt`. Since someone on our team would be maintaining this code at all times, we would like to have a similar setup in place even for Java. Right now, we have a gradle task `./gradlew goJF` which formats the source code. We could add a commit hook to make this automated. Beyond that, I would like to avoid any formatting related stuff in the repo (like `.editorconfig`). IntelliJ Idea has a `google-java-format` plugin which you could use. If you still want to use `.editorconfig`, maybe we could just add it to .gitignore so that it does not get committed to the repo.

**Comment by deepakjois** [comment]
I am going to close this, because this is a bit outdated. The Github issue remains open.

**Pull request closed without merging**
