### PR TITLE
added async client implementation

### PR DESCRIPTION
**Pull request by thestarmaker**
I have added an async client. The synchronous version just delegates to async and blocks the caller thread until the async fulfills. Please review, let me know if anything is overcooked.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph4j/60)

### CODE REVIEW

**Comment by deepakjois** [comment]
Sorry for the delay in getting to this.

I reviewed the change in detail and it looks very polished. So I expect it to go in without many changes. I cherry-picked your changes in another branch, and added some minor tests on top. I will also add some documentation and update the examples. Once all of that has been completed, the changes will be merged to master and a new release will be made.

You can view the changes here: https://github.com/dgraph-io/dgraph4j/tree/dj-async-client

**Comment by thestarmaker** [comment]
@deepakjois thanks; I added a comment:
https://github.com/dgraph-io/dgraph4j/commit/084f3c448e9c09fe6aae5b1d29f93176385ce543

**Comment by deepakjois** [comment]
@thestarmaker Thanks for your comment. I made some changes to the test to use `thenCompose`. It seems to also make the assertions work properly.

I have also added some documentation. It is ready for merging into master. I will wait for a few hours to see if you have any further comments before merging.

**Comment by deepakjois** [comment]
This PR is merged as 1658caf5c5829ce823a3e6d9b316dcd225d61f41

**Pull request closed without merging**
